# Generated by Django 5.2.4 on 2025-07-07 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=30)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=80)),
                ('respuesta_pregunta1', models.CharField(max_length=20)),
                ('respuesta_pregunta2', models.CharField(max_length=10)),
                ('respuesta_preguntaA', models.CharField(blank=True, max_length=10, null=True)),
                ('respuesta_preguntaB', models.CharField(blank=True, max_length=10, null=True)),
                ('respuesta_preguntaC', models.CharField(blank=True, max_length=10, null=True)),
                ('respuesta_pregunta_comentarios', models.CharField(max_length=300)),
            ],
        ),
    ]
